version: "3.8"
services:
  jugtoursdb:
    container_name: jugtoursdb
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jugtoursdb
    ports:
      - '5432:5432'

volumes:
  postgres_data: